### ISSUE TITLE
CUDA config

### ISSUE THREAD

**Issue by d-li14** [yangsenius/learning-to-learn-by-pytorch#1]
@yangsenius Thanks for your helpful implementation. There seems a minor bug during runtime.
The line for [CUDA configuration](https://github.com/yangsenius/learning-to-learn-by-pytorch/blob/master/learning_to_learn.py#L22) is redundant to avoid potential GPU utilization.

**Comment by yangsenius** [comment]
Yeah, this flag can be removed for your need @d-li14
