### ISSUE TITLE
Optimizer instead of optimizee?

### ISSUE THREAD

**Issue by rahulbhadani** [yangsenius/learning-to-learn-by-pytorch#2]
Hello, 
         It seems in the `learn` function, the variable name should be `optimizer` instead of `optimizee` as LSTM is an optimizer and not optimizee. Can you clarify this? 

I have some confusion here.

Thanks.
Rahul

**Comment by yangsenius** [comment]
Hi, 
yes, in the paper, LSTM is viewed as an `optimizer` to model parameters, `f` is viewed as `optimizee`.  So here naming LSTM optimizer as `optimizee` is a little inconsistent with the paper. I will update this.
